// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZfexEvzTkjdf6V8MxvzcSvb8mgKPOZg',
    appId: '1:909041551627:web:18f75c4c6ee68d0ae83a0e',
    messagingSenderId: '909041551627',
    projectId: 'elpris-velkommen',
    authDomain: 'elpris-velkommen.firebaseapp.com',
    databaseURL: 'https://elpris-velkommen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elpris-velkommen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdGi1SUV-jfZGAcWBjzdFNrE-YVkv3d90',
    appId: '1:909041551627:android:fcbce79d610c9598e83a0e',
    messagingSenderId: '909041551627',
    projectId: 'elpris-velkommen',
    databaseURL: 'https://elpris-velkommen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elpris-velkommen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs97Qz8WD-x6IUTsR2agzSmbq9xtijvUE',
    appId: '1:909041551627:ios:5b5671c004c2f733e83a0e',
    messagingSenderId: '909041551627',
    projectId: 'elpris-velkommen',
    databaseURL: 'https://elpris-velkommen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elpris-velkommen.appspot.com',
    iosClientId: '909041551627-uqbdgk0dedgqfjt8l7i7ivebfvs876hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.elprisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs97Qz8WD-x6IUTsR2agzSmbq9xtijvUE',
    appId: '1:909041551627:ios:5b5671c004c2f733e83a0e',
    messagingSenderId: '909041551627',
    projectId: 'elpris-velkommen',
    databaseURL: 'https://elpris-velkommen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elpris-velkommen.appspot.com',
    iosClientId: '909041551627-uqbdgk0dedgqfjt8l7i7ivebfvs876hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.elprisApp',
  );
}
